#!/usr/bin/env python3
"""Utilities for applying LeRobot ACT pose actions to UR-style TCP poses.

The default convention matches scripts/convert_ur5e_to_lerobot.py:

    action_pose_delta = [
        delta_tcp_x, delta_tcp_y, delta_tcp_z,
        delta_tcp_rx, delta_tcp_ry, delta_tcp_rz,
    ]

Translation deltas are in the robot/base coordinate frame. Rotation deltas are
relative SO(3) rotation vectors, where:

    R_next = R_current @ exp(delta_rotvec)

The returned pose is UR-style [x, y, z, rx, ry, rz].
"""

from __future__ import annotations

import math
from collections.abc import Sequence

import numpy as np


def apply_pose_delta(
    current_pose: Sequence[float],
    action_pose_delta: Sequence[float],
    rotation_delta_mode: str = "relative-rotvec",
) -> list[float]:
    """Apply a pose delta action to a UR-style TCP pose.

    Args:
        current_pose: Current TCP pose as [x, y, z, rx, ry, rz]. The last
            three values are UR rotation-vector components.
        action_pose_delta: Pose part of the action. The first six values are
            [dx, dy, dz, drx, dry, drz]. If a longer action is provided, such
            as one that also includes gripper delta, the extra values are
            ignored.
        rotation_delta_mode: Use "relative-rotvec" for actions generated by
            the default converter. Use "raw-rotvec" only if the action was
            created by directly subtracting UR rx/ry/rz components.

    Returns:
        Target TCP pose as [x, y, z, rx, ry, rz].
    """

    pose = np.asarray(current_pose, dtype=np.float64)
    delta = np.asarray(action_pose_delta, dtype=np.float64)

    if pose.shape[0] != 6:
        raise ValueError(f"current_pose must have 6 values, got {pose.shape[0]}")
    if delta.shape[0] < 6:
        raise ValueError(f"action_pose_delta must have at least 6 values, got {delta.shape[0]}")

    next_position = pose[:3] + delta[:3]

    if rotation_delta_mode == "relative-rotvec":
        current_rot = rotvec_to_matrix(pose[3:6])
        delta_rot = rotvec_to_matrix(delta[3:6])
        next_rotvec = matrix_to_rotvec(current_rot @ delta_rot)
    elif rotation_delta_mode == "raw-rotvec":
        next_rotvec = pose[3:6] + delta[3:6]
    else:
        raise ValueError(
            "rotation_delta_mode must be 'relative-rotvec' or 'raw-rotvec', "
            f"got {rotation_delta_mode!r}"
        )

    return [*next_position.tolist(), *next_rotvec.tolist()]


def rotvec_to_matrix(rotvec: Sequence[float]) -> np.ndarray:
    """Convert a rotation vector to a 3x3 rotation matrix."""

    rotvec = np.asarray(rotvec, dtype=np.float64)
    theta = float(np.linalg.norm(rotvec))
    if theta < 1e-12:
        return np.eye(3, dtype=np.float64)

    axis = rotvec / theta
    skew = np.array(
        [
            [0.0, -axis[2], axis[1]],
            [axis[2], 0.0, -axis[0]],
            [-axis[1], axis[0], 0.0],
        ],
        dtype=np.float64,
    )
    return (
        np.eye(3, dtype=np.float64)
        + math.sin(theta) * skew
        + (1.0 - math.cos(theta)) * (skew @ skew)
    )


def matrix_to_rotvec(matrix: np.ndarray) -> np.ndarray:
    """Convert a 3x3 rotation matrix to a canonical rotation vector."""

    matrix = np.asarray(matrix, dtype=np.float64)
    cos_theta = (float(np.trace(matrix)) - 1.0) / 2.0
    cos_theta = min(1.0, max(-1.0, cos_theta))
    theta = math.acos(cos_theta)

    if theta < 1e-12:
        return np.zeros(3, dtype=np.float64)

    vector = np.array(
        [
            matrix[2, 1] - matrix[1, 2],
            matrix[0, 2] - matrix[2, 0],
            matrix[1, 0] - matrix[0, 1],
        ],
        dtype=np.float64,
    )

    if abs(math.pi - theta) < 1e-5:
        axis = np.empty(3, dtype=np.float64)
        axis[0] = math.sqrt(max(0.0, (matrix[0, 0] + 1.0) / 2.0))
        axis[1] = math.sqrt(max(0.0, (matrix[1, 1] + 1.0) / 2.0))
        axis[2] = math.sqrt(max(0.0, (matrix[2, 2] + 1.0) / 2.0))
        axis[1] = math.copysign(axis[1], matrix[0, 1] + matrix[1, 0])
        axis[2] = math.copysign(axis[2], matrix[0, 2] + matrix[2, 0])
        norm = float(np.linalg.norm(axis))
        if norm < 1e-12:
            return np.zeros(3, dtype=np.float64)
        return theta * axis / norm

    return theta * vector / (2.0 * math.sin(theta))


if __name__ == "__main__":
    current = [-0.039181, -0.733251, 0.529441, -0.063563, -3.123261, 0.052744]
    delta = [-0.000022, -0.000013, -0.000011, 0.000030111, 0.000007234, 0.000024567]
    print(apply_pose_delta(current, delta))
